import Head from 'next/head';
import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={props.results} />

    </div>
  )
}

export async function getServerSideProps(context){
  const gener = context.query;
  const request = await fetch(`https://pixabay.com/api/?key=${process.env.API_KEY}&q=${gener.genre||'popular'}&orientation=horizontal`)
  .then((res) => res.json());
  return {
    props: {
      results: request || null,
      gener:gener || null,
    }
  }
}